services:
  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: ["sh", "-c", "rm -f tmp/pids/server.pid && ruby bin/rails server -b 0.0.0.0"]
    environment:
      RAILS_ENV: ${RAILS_ENV}
      COINGECKO_API_KEY: ${COINGECKO_API_KEY}
      MEMCACHED_URL: memcached:11211
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
      - storage_data:/rails/storage
    depends_on:
      - memcached
    tty: true
    stdin_open: true

volumes:
  bundle_data:
  storage_data:
